settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: BOOKS_API
    path: .
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
